#!/bin/sh
set -e

if [ x"$1" = xconfigure ]; then
  if [ -f /etc/inittab ]; then
    if ! grep '^SV:' /etc/inittab >/dev/null; then
      echo 'Adding SV inittab entry...'
      (
        cat /etc/inittab
        echo '#-- daemontools-run begin'
        echo 'SV:123456:respawn:/usr/bin/svscanboot'
        echo '#-- daemontools-run end'
      ) > /etc/inittab'{new}'
      mv -f /etc/inittab'{new}' /etc/inittab
      init q || :
    fi
  fi
fi

#DEBHELPER#
